# Generated by Django 2.1.2 on 2018-10-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete='self', to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete='self', related_name='contents', to='courses.Module')),
            ],
        ),
    ]
